In [1]:
import numpy as np

In [ ]:
list1 = [1, 2, 3]
a = np.array(list1) # np.arrau([1, 2, 3])
print(a)
print(type(a))
print(a.shape)
a[0] = -1
print(a)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
[-1  2  3]


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c.shape)
print(b[0, 1], c[1, 1, 0])


(2, 3)
(2, 2, 3)
2 10


In [17]:
a = np.array([1, 2, 3, 4, 5])
d = a[1:].copy() # 'd' is a view of 'a'
d[1] = 100
print(d, a)

[  2 100   4   5] [1 2 3 4 5]


In [ ]:
a = np.full((2, 3, 4), 42) # zeros ones
print(a)

[[[42 42 42 42]
  [42 42 42 42]
  [42 42 42 42]]

 [[42 42 42 42]
  [42 42 42 42]
  [42 42 42 42]]]


In [21]:
identity_matrix = np.eye(8)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [22]:
e = np.random.random((2, 3)) # uniform distribution in [0, 1)
print(e)

[[0.59388482 0.91682338 0.63016827]
 [0.42277511 0.62338447 0.60962845]]


In [25]:
s = np.linspace(0, 1, 5) # 5 numbers between 0 and 1
print(s)
t = np.arange(0, 1, 0.1) # [0, 1) with step 0.2
print(t)

[0.   0.25 0.5  0.75 1.  ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [31]:
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_index = a > 2
print(bool_index)
print(a[bool_index])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.eye(2)
print(x.dot(z))
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
print(x.T) # transpose

[[1. 2.]
 [3. 4.]]
10
[4 6]
[3 7]
[[1 3]
 [2 4]]


In [ ]:
v = np.array([1,2,3,4,5,6])
print(np.reshape(v, (3, 2))) # broadcasting

[[1 2]
 [3 4]
 [5 6]]
